apiVersion: v1
kind: Pod
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
spec:
  securityContext:
    runAsUser: 10000
  containers:
  - name: libeopp-build
    image: cgici/eopp-build-container:2.0.1
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
